### ISSUE TITLE
Cannot read properties of null (reading 'push')

### ISSUE THREAD

**Issue by aral** [dy/xhtm#15]
## Reproduction

```js
html`
  <input x-init='$nextTick(_ => {
    $el.value = localStorage.getItem("secret")
  })' :type='showSecret ? "input" : "password"'></input>
`
```

(Where `html` is `xhtm.bind(vhtml)`.)

## Error

```
TypeError: Cannot read properties of null (reading 'push')
    at up (file:///var/home/aral/Projects/other/xhtm/htm.js:25:13)
    at file:///var/home/aral/Projects/other/xhtm/htm.js:72:9
    at String.replace (<anonymous>)
    at Function.htm (file:///var/home/aral/Projects/other/xhtm/htm.js:35:6)
```

## Version

1.5.10 (the issue is also present in earlier versions)

**Comment by aral** [comment]
PS. Just went through all the Kitten examples and tested [Domain](https://codeberg.org/domain/app) as well (a real-world Kitten app) and everything seems to be working except for this :)

PPS. I cannot express in words how much I appreciate how amazing you’ve been with helping me on this, Dmitry. Thank you so much. I hope my surfacing all these issues hasn’t been too annoying. This is going to make a world of difference to the experience of folks authoring Small Web apps  in the future. :two_hearts:

**Comment by dy** [comment]
Yeah, it's not very resilient to invalid input... In HTML input is not pair-tag, it's self-closing or empty tag, ie. `<input/>` or `<input>`. So that `</input>` is not fully valid.
Anyways. take 1.5.11 - it has that fixed.

**Comment by dy** [comment]
You're welcome, thanks for the input, you got the library to more production-ready level.

**Comment by aral** [comment]
> Yeah, it's not very resilient to invalid input... In HTML input is not pair-tag, it's self-closing or empty tag, ie. `<input/>` or `<input>`. So that `</input>` is not fully valid. Anyways. take 1.5.11 - it has that fixed.

*blush*, you’d think I‘d know that having written the darn thing for nigh on three decades now – thanks so much, working like a charm now :)
