### ISSUE TITLE
Regression: HTML boolean attributes being written out as ="true"

### ISSUE THREAD

**Issue by aral** [dy/xhtm#18]
HTML boolean attributes (e.g., `hidden`) are being written out as `="true"`.

## Reproduction

```js
import xhtm from 'xhtm'
import vhtml from 'vhtml' 
const html = xhtm.bind(vhtml)

const markup = html`<main hidden></main>`

console.log(markup)
```

## Expected output

```html
<main hidden></main>
```

## Actual output

```html
<main hidden="true"></main>
```

## Version

1.5.14

**Comment by dy** [comment]
That's totally up to vhtml.
HTM has same behavior.
The markup returned by xhtm is `h('main', {hidden: true})`, it can't be more correct.

**Comment by aral** [comment]
Thanks @dy. Having a look at vhtml now with an eye towards making some changes ;)

**Comment by aral** [comment]
In case it helps anyone else who finds themselves here, I forked Jason’s excellent vhtml and added a few things I need here:

https://codeberg.org/small-tech/vhtml

Specifically, so far:

- Style tags are no longer escaped
- Boolean HTML attributes are emitted correctly (without `="true"`)
