### ISSUE TITLE
Redundant logical OR in regexp

### ISSUE THREAD

**Issue by aral** [dy/xhtm#24]
Unless I’m missing something, the OR at https://github.com/dy/xhtm/blob/master/htm.js#L91 is redundant (both sides are the same).

**Comment by dy** [comment]
Ah, right, that's artifact from `/(?<=^|>|\ue000)\s*\n\s*|\s*\n\s*(?=$|<|\ue000)/g`. Good to go for me!

**Comment by aral** [comment]
Hey Dmitry, I thought it was something like that :) (I also verified the regular expression equivalence via https://bakkot.github.io/dfa-lib/regeq.html just in case.)

Hope you’re having a lovely weekend :)
