### ISSUE TITLE
Different output from htm when used with vhtml

### ISSUE THREAD

**Issue by aral** [dy/xhtm#7]
Hi there,

I just tried replacing [htm](https://github.com/developit/htm) with xhtm and it looks like xhtm is generating different output when bound to [vhtml](https://github.com/developit/vhtml):

e.g., For the basic [Counting Kittens example](https://codeberg.org/kitten/app#counting-kittens) in Kitten:

```js
let count = 1

export default _ => (
  html`
    <h1>Kitten count<h1>
    <p>${'😸️'.repeat(count++)}</p>
  `
)
```

When `html` uses htm:

```js
import htm from 'htm'
import vhtml from 'vhtml'
globalThis.html = htm.bind(vhtml)
```

I get:

```js
[ '<h1>Kitten count</h1>', '<p>😸️</p>' ]
```

When `html` uses xhtm:

```js
import htm from 'xhtm'
import vhtml from 'vhtml'
globalThis.html = htm.bind(vhtml)
```

I get:

```js
[ '<h1>Kitten count</h1>', '<p>😸️</p>', root: true ]
```

(Note the additional `root: true`.)

**Comment by aral** [comment]
@dy I thought it was but now I’m not sure if that’s the problem or not. Basically, with vhtml bound to htm, I’m able to nest calls to the `html` tagged template but with xhtm that doesn’t seem to be working. I think I’m going to leave it for now and reevaluate it at at a later date :)

**Comment by dy** [comment]
Ok, just rebuilt without `root` reference.
Hope can help.

**Comment by aral** [comment]
Thanks so much @dy, appreciate it. Will give it a shot today :)

**Comment by aral** [comment]
@dy Thanks again! I’ve got nearly everything working exactly the same was as htm with xhtm in Kitten. Just one issue remaining (nested calls to xhtm’s `html` – e.g., when doing a `map()` inside the template – when bound to `vhtml` result in additional commas being added in the output). I’ll open a separate issue for that but I’m 99% sure I want to go with xhtm now because it is just so much easier to work with (JavaScript not TypeScript, not over-optimised; I’m actually able to follow the code) and because it focuses on (forgiving) HTML instead of strict JSX :)

**Comment by dy** [comment]
Thanks! It would be helpful to see the problem, I will add a test.
