### ISSUE TITLE
Zero is translated as empty string when htm is bound to vhtml

### ISSUE THREAD

**Issue by aral** [dy/xhtm#8]
This issue also affects htm:
https://github.com/developit/htm/issues/241

**Comment by dy** [comment]
This seems to be a specifics of vhtml though

**Comment by aral** [comment]
@dy Agree; please feel free to close this (and thanks for the link to hyperf; will check it out) :)

**Comment by aral** [comment]
@dy Had a quick play with hyperf but it looks like it’s browser-only (failed while looking for document). I’m using vhtml to render on the server :)
