### ISSUE TITLE
Additional comma added by xhtm

### ISSUE THREAD

**Issue by aral** [dy/xhtm#9]
xhtm bound to vhtml adds an additional comma during string interpolation within attribute values.

## To reproduce

```js
import htm from 'htm'
import xhtm from 'xhtm'
import vhtml from 'vhtml'

const htmlHtm = htm.bind(vhtml)
const htmlXhtm = xhtm.bind(vhtml)

const titles = ['one', 'two', 'three']

const ComponentHtm = ({title, index}) => htmlHtm`
  <li src='https://my.site/section/${index+1}'>
    Section ${index+1}: ${title}
  </li>
`
const ComponentXhtm = ({title, index}) => htmlXhtm`
  <li src='https://my.site/section/${index+1}'>
    Section ${index+1}: ${title}
  </li>
`

const htmlFromHtm = htmlHtm`
  <ul>
    ${titles.map((title, index) => htmlHtm`<${ComponentHtm} title=${title} index=${index} />`)}
  </ul>

`
const htmlFromXhtm = htmlXhtm`
  <ul>
    ${titles.map((title, index) => htmlXhtm`<${ComponentXhtm} title=${title} index=${index} />`)}
  </ul>
`

console.info('HTML from htm\n\n', htmlFromHtm)
console.info('\nHTML from xhtm\n\n', htmlFromXhtm)
```

## Expected output

Both results should match:

```
 <ul><li src="https://my.site/section/1">Section 1: one</li><li src="https://my.site/section/2">Section 2: two</li><li src="https://my.site/section/3">Section 3: three</li></ul>
```

## Actual output

```
HTML from htm

 <ul><li src="https://my.site/section/1">Section 1: one</li><li src="https://my.site/section/2">Section 2: two</li><li src="https://my.site/section/3">Section 3: three</li></ul>

HTML from xhtm

 <ul> <li src="https://my.site/section/,1"> Section 1: one </li><li src="https://my.site/section/,2"> Section 2: two </li><li src="https://my.site/section/,3"> Section 3: three </li> </ul>
```

Note the commas before the indices in the `src` attributes.

_(Minor: Also note that xhtm is adding some additional spaces inside the  the `<li>` tags and between the `<ul>` and `<li>` tags but this is ignored by browsers and does not affect the content viewed in the browser.)_

**Comment by aral** [comment]
So now I’m confused.

I added the following test to `test/index.js` and it’s passing:

```js
import htmOriginal from 'htm'
const htmOriginalBound = htmOriginal.bind(h)

t('component', t => {
	const titles = ['one', 'two', 'three']
	const componentXhtm = ({title, index}) => html`<li src='https://my.site/section/${index+1}'>Section ${index+1}: ${title}</li>`
	const resultXhtm = html`<ul>${titles.map((title, index) => html`<${componentXhtm} title=${title} index=${index} />`)}</ul>`
	const componentHtm = ({title, index}) => htmlmOriginalBound`<li src='https://my.site/section/${index+1}'>Section ${index+1}: ${title}</li>`
	const resultHtm = htmOriginalBound`<ul>${titles.map((title, index) => htmOriginalBound`<${componentXhtm} title=${title} index=${index} />`)}</ul>`
	t.deepEqual(resultXhtm,resultHtm, 'The output should be the same')
})
```

**Comment by dy** [comment]
FYI I just fixed the issue, not published to npm yet.

**Comment by aral** [comment]
Wow, thank you so much, Dmitry. I can’t wait to try it out tomorrow :)

**Comment by aral** [comment]
@dy 1.5.5 seems to have broken components. I’m going to take a proper look at it later but one piece of code at least seems to have an obvious error in it (unless I’m missing something) – although fixing that doesn’t help with the component issue:

https://github.com/dy/xhtm/commit/1e139e229b2f22a7601f35c970f93bc0481cf10c#r102054115

**Comment by dy** [comment]
Oh, ok. I need test case then. It looks like existing tests pass.

**Comment by aral** [comment]
@dy I’m looking into it now. There are a few places where it seems to have broken the Kitten examples. Will prepare a test case or cases.

The error I’m seeing, by the way, is `TypeError: value.join is not a function` while running `Array.Array.isArray.value.toString` in _/htm.js_ (line 66, column 47) when it tries to render a component. With that particular component, it seems to be trying to call `join()` on a string.

**Comment by aral** [comment]
I narrowed it down and opened a separate issue: https://github.com/dy/xhtm/issues/10 :)

**Comment by dy** [comment]
Yes, thanks! Fixed
